import os
import sys
import streamlit as st

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from src.config import settings
from src.state import init_session_state, inject_css, render_stepper, next_step_banner, guard_prerequisite
from src.agents.insights_agent import BusinessInsightsAgent

st.set_page_config(page_title="Business Insights", page_icon="💡", layout="wide")
init_session_state()
inject_css()
render_stepper("insights")
guard_prerequisite("insights", "⚠️ Please train a model first so there are metrics to interpret.")

st.title("💡 Automated Business Insights")

if settings.llm_enabled:
    st.success("🟢 Connected to Groq — narratives will be generated by an LLM.")
else:
    st.warning("🟡 No `GROQ_API_KEY` found. Insights will use the built-in offline template generator — fully functional, just less nuanced. Add a free key from console.groq.com/keys to your `.env` file to upgrade.")

if st.button("▶ Generate Business Insights", type="primary"):
    with st.status("💡 Business Insights Agent writing narrative...", expanded=True) as status:
        agent = BusinessInsightsAgent()
        ok, out = agent.run(
            st.session_state.dataset_name, st.session_state.task_type,
            st.session_state.metrics, st.session_state.feature_importances, st.session_state.industry,
        )
        st.session_state.narrative = out["narrative"]
        st.session_state.recommendations = out["recommendations"]
        st.session_state.narrative_source = out["source"]
        status.update(label=f"Insights generated via {out['source']} ✅", state="complete")

if st.session_state.narrative:
    st.divider()
    badge = "🤖 Groq LLM" if st.session_state.narrative_source == "groq" else "📋 Offline template"
    st.caption(f"Source: {badge}")

    st.subheader("Executive Narrative")
    st.markdown(f'<div class="agent-card">{st.session_state.narrative.replace(chr(10), "<br>")}</div>', unsafe_allow_html=True)

    st.subheader("Strategic Recommendations")
    st.markdown(f'<div class="agent-card">{st.session_state.recommendations.replace(chr(10), "<br>")}</div>', unsafe_allow_html=True)

    st.divider()
    next_step_banner("insights")
    if st.button("Proceed to Reports Hub →", type="primary"):
        st.switch_page("pages/6_Reports_Hub.py")
